---
version: '3.3'
services:
  cloudlib: &app
    image: spiffycell/cloudlib 
    build:
      context: src/
      args:
        - VERSION=${VERSION} commit ${VCS_REF}

  linter:
    <<: *app
    entrypoint: /opt/app/linter

  tester:
    <<: *app
    entrypoint: /opt/app/test
    env_file: ~/.env
    environment:
      - CI
      - DEBUG
