version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.17
    steps:
      - checkout
      - run:
          name: "bootstrap"
          command: "cicd/bootstrap"
      - run:
          name: "build"
          command: "cicd/build"
      - run:
          name: "test"
          command: "cicd/test"
      - run:
          name: "publish"
          command: "cicd/publish"
