version: 2.1

jobs:
  build:
    working_directory: ~/cloudlib/
    machine:
      - image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run:
          name: "bootstrap the env"
          command: cicd/bootstrap
      - run:
          name: "build the image"
          command: cicd/build
      - run:
          name: "test the build"
          command: cicd/test
      - run:
          name: "publish the image"
          command: cicd/publish
