#!/bin/bash

set -eEu
set -o pipefail

# first we want to specify the build vars
# and store them in a vars file which we can reference later
echo
echo Declare our build vars
cat >cicd/vars <<EOF
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git describe --abbrev=7 --tags --always)
export TAG=$(date +%Y%m%d.%H%M)
export CI_BUILD_URL=${CI_BUILD_URL:-unset}
EOF

echo
echo Initialize our build vars
. cicd/vars

# build the image 
echo
echo Build the image
docker-compose build

# check if image was built successfully
echo
echo Check image was built successfully
docker images | grep 'spiffycell/cloudlib'
