#!/usr/bin/python3
""" Test ."""

import logging
import signal
import sys

def test_boolean_envs():
    """ Test truthy/falsy values."""
    truthy = [
        "y",
        "yes",
        " y",
        "y ",
        "true"
    ]
    falsy = [
        "n",
        "no",
        " n",
        "n ",
        "false"
    ]

    # then we need to assert these values
    # are truthy / falsy
	return

def test_module_methods():
    test_postgres_methods()
    test_vault_methods()


if __name__ == "__main__":
    """ Initialize tests."""
	test_boolean_envs()
    test_module_methods()
