#!/usr/bin/python3
""" Test file."""

# standard imports
import logging
import signal
import sys

# non-standard imports
from utils import config_logs


def test_boolean_envs():
    """ Test truthy/falsy values."""
    # we need to assert truthy / falsy values
    # these is our sanity-testing framework
    # https://realpython.com/python-assert-statement/

    # declare set of truthy/falsy statements
    truthy = [
        "y",
        "yes",
        " y",
        "y ",
        "true"
    ]
    falsy = [
        "n",
        "no",
        " n",
        "n ",
        "false"
    ]

	return

def test_postgres_methods():
    """ Test methods of our Postgres class."""
    return

def test_vault_methods():
    """ Test methods of our Vault class."""
    return

def test_module_methods():
    """ Test methods of each of the modules in cloudlib."""
    test_postgres_methods()
    test_vault_methods()


if __name__ == "__main__":
    """ Initialize tests."""
    config_logs("cloudlib test")
	test_boolean_envs()
    test_module_methods()
